# SPDX-FileCopyrightText: 2022 Great Software Laboratory Pvt. Ltd
# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0


---
info:
  version: 1.0.0
  description: GNBSIM initial local configuration

configuration:
  runConfigProfilesAtStart: true
  pauseAtStart: true
  singleInterface: false			# Default value
  execInParallel: true				# Run all profiles in parallel
  httpServer:					# API to manage profiles at runtime
    enable: false
    port: 8080
  gnbs:						# Pool of gNBs
    gnb1:
      n2IpAddr:					# N2 IPaddr to connect to AMF
      #n2Port: 9487				# N2 Port to connect to AMF
      #n3IpAddr: "POD_IP"			# Use when in singleInterface mode
      #n3Port: 2152 #{ { container_port } }	# N3 Port to connect to UPF
      name: gnb1				# Uniquely identify gNB within application
      globalRanId:
        plmnId:
          mcc: 208				# Mobile Country Code
          mnc: 93				# Mobile Network Code
        gNbId: 
          bitLength: 24
          gNBValue: "001001"			# gNB id (3 bytes/hex: range 000000~FFFFFF)
      supportedTaList:
        - tac: 000001				# TAC (3 bytes/hex: range: 000000~FFFFFF)
          broadcastPlmnList:
            - plmnId:
                mcc: 208
                mnc: 93
              taiSliceSupportList:
                - sst: 1			# Slice/Service Type (uinteger: range 0~255)
                  sd: 010203			# Slice Differentiator (3 bytes/hex)
                - sst: 1
                  sd: 000001
                - sst: 2
      defaultAmf:
        hostName: amf				# Host name of AMF
        ipAddr: "172.16.49.16"			# AMF IP address
        port: 35412				# AMF port


  # See https://github.com/omec-project/gnbsim
  #   for a description of the supported profiles
  # Parameters documented above (in comments on Custom Profile)
  # Profile 2 (pdusessest) typically enabled by default

  profiles:
  - profileType: register	# UE Registration
    profileName: profile1
    enable: true
    gnbName: gnb1
    execInParallel: true
    startImsi: 208930000000001 
    ueCount: 10
    defaultAs: "192.168.250.1"
    perUserTimeout: 100
    plmnId:
      mcc: 208
      mnc: 93
    opc: "981d464c7c52eb6e5036234984ad0bcf"
    key: "5122250214c33e723a5dd523fc145fc0"
    sequenceNumber: "16f3b3f70fc2"

# Set logging level
logger:
  logLevel: info		# trace, debug, info, warn, error, fatal, panic

